baseURL: "https://ibpsa-vietnam.netlify.app"
defaultContentLanguage: vi
defaultContentLanguageInSubdir: false

languages:
  en:
    languageCode: en-us
    languageName: English
    weight: 2
    title: "IBPSA Vietnam"
    params:
      description: "International Building Performance Simulation Association - Vietnam Chapter"
      author: "IBPSA Vietnam"
      email: "info@ibpsa-vietnam.org"
      phone: "+84 xxx xxx xxxx"
      address: "Vietnam"
      social:
        facebook: "https://facebook.com/ibpsa.vietnam"
        linkedin: "https://linkedin.com/company/ibpsa-vietnam"
        twitter: "https://twitter.com/ibpsa_vietnam"
      logo: "/images/ibpsa-vietnam-logo.png"
      favicon: "/images/favicon.ico"
    menu:
      main:
        - name: "Home"
          url: "/en/"
          weight: 10

        - name: "About"
          url: "/en/about/"
          weight: 20
          hasChildren: true

        - name: "Membership"
          url: "/en/membership/"
          weight: 30
          hasChildren: true

        - name: "Events"
          url: "/en/events/"
          weight: 40
          hasChildren: true

        - name: "Resources"
          url: "/en/resources/"
          weight: 50
          hasChildren: true

        - name: "News"
          url: "/en/news/"
          weight: 60
          hasChildren: true

        - name: "Collaboration"
          url: "/en/collaboration/"
          weight: 70
          hasChildren: true

        - name: "Career"
          url: "/en/career/"
          weight: 80
          hasChildren: true

        - name: "Contact"
          url: "/en/contact/"
          weight: 90

  vi:
    languageCode: vi-vn
    languageName: Tiếng Việt
    weight: 1
    title: "IBPSA Việt Nam"
    params:
      description: "Hiệp hội Mô phỏng Hiệu suất Tòa nhà Quốc tế - Chi hội Việt Nam"
      author: "IBPSA Việt Nam"
      email: "info@ibpsa-vietnam.org"
      phone: "+84 xxx xxx xxxx"
      address: "Việt Nam"
      social:
        facebook: "https://facebook.com/ibpsa.vietnam"
        linkedin: "https://linkedin.com/company/ibpsa-vietnam"
        twitter: "https://twitter.com/ibpsa_vietnam"
      logo: "/images/ibpsa-vietnam-logo.png"
      favicon: "/images/favicon.ico"
    menu:
      main:
        - name: "Trang chủ"
          url: "/"
          weight: 10

        - name: "Giới thiệu"
          url: "/about/"
          weight: 20
          hasChildren: true

        - name: "Thành viên"
          url: "/membership/"
          weight: 30
          hasChildren: true

        - name: "Sự kiện"
          url: "/events/"
          weight: 40
          hasChildren: true

        - name: "Tài nguyên"
          url: "/resources/"
          weight: 50
          hasChildren: true

        - name: "Tin tức"
          url: "/news/"
          weight: 60
          hasChildren: true

        - name: "Hợp tác"
          url: "/collaboration/"
          weight: 70
          hasChildren: true

        - name: "Nghề nghiệp"
          url: "/career/"
          weight: 80
          hasChildren: true

        - name: "Liên hệ"
          url: "/contact/"
          weight: 90

      about:
        - name: "Sứ mệnh & Tầm nhìn"
          url: "/about/mission/"
          parent: "about"
          weight: 10

        - name: "Hội đồng quản trị"
          url: "/about/board/"
          parent: "about"
          weight: 20

        - name: "Các ủy ban"
          url: "/about/committees/"
          parent: "about"
          weight: 30

        - name: "Lịch sử"
          url: "/about/history/"
          parent: "about"
          weight: 40

        - name: "Báo cáo thường niên"
          url: "/about/reports/"
          parent: "about"
          weight: 50

      membership:
        - name: "Tham gia IBPSA Việt Nam"
          url: "/membership/join/"
          parent: "membership"
          weight: 10

        - name: "Lợi ích"
          url: "/membership/benefits/"
          parent: "membership"
          weight: 20

        - name: "Danh sách thành viên"
          url: "/membership/directory/"
          parent: "membership"
          weight: 30

        - name: "Phí"
          url: "/membership/fees/"
          parent: "membership"
          weight: 40

      events:
        - name: "Sự kiện sắp tới"
          url: "/events/upcoming/"
          parent: "events"
          weight: 10

        - name: "Sự kiện đã qua"
          url: "/events/archive/"
          parent: "events"
          weight: 20

        - name: "Hội thảo trực tuyến"
          url: "/events/webinars/"
          parent: "events"
          weight: 30

        - name: "Hội thảo"
          url: "/events/workshops/"
          parent: "events"
          weight: 40

      resources:
        - name: "Xuất bản"
          url: "/resources/publications/"
          parent: "resources"
          weight: 10

        - name: "Hướng dẫn"
          url: "/resources/guidelines/"
          parent: "resources"
          weight: 20

        - name: "Phần mềm & Công cụ"
          url: "/resources/tools/"
          parent: "resources"
          weight: 30

        - name: "Nghiên cứu điển hình"
          url: "/resources/case-studies/"
          parent: "resources"
          weight: 40

        - name: "Tiêu chuẩn"
          url: "/resources/standards/"
          parent: "resources"
          weight: 50

      news:
        - name: "Tin tức mới nhất"
          url: "/news/"
          parent: "news"
          weight: 10

        - name: "Bản tin"
          url: "/news/newsletter/"
          parent: "news"
          weight: 20

        - name: "Thông báo"
          url: "/news/announcements/"
          parent: "news"
          weight: 30

      collaboration:
        - name: "Đối tác học thuật"
          url: "/collaboration/academic/"
          parent: "collaboration"
          weight: 10

        - name: "Đối tác công nghiệp"
          url: "/collaboration/industry/"
          parent: "collaboration"
          weight: 20

        - name: "Quan hệ chính phủ"
          url: "/collaboration/government/"
          parent: "collaboration"
          weight: 30

        - name: "Dự án nghiên cứu"
          url: "/collaboration/research/"
          parent: "collaboration"
          weight: 40

      career:
        - name: "Bảng việc làm"
          url: "/career/jobs/"
          parent: "career"
          weight: 10

        - name: "Giáo dục"
          url: "/career/education/"
          parent: "career"
          weight: 20

        - name: "Chứng chỉ"
          url: "/career/certification/"
          parent: "career"
          weight: 30

        - name: "Phát triển chuyên môn"
          url: "/career/development/"
          parent: "career"
          weight: 40

      footer:
        - name: "Chính sách bảo mật"
          url: "/privacy/"
          weight: 10

        - name: "Điều khoản dịch vụ"
          url: "/terms/"
          weight: 20

        - name: "Sơ đồ trang web"
          url: "/sitemap/"
          weight: 30

googleAnalytics: ""

# SEO and social media
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: "github"
    tabWidth: 2

# Output formats
outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]
  section: ["HTML", "RSS"]

# Menu configuration with submenus
menu:
  about:
    - name: "Mission & Vision"
      url: "/about/mission/"
      parent: "about"
      weight: 10

    - name: "Board of Directors"
      url: "/about/board/"
      parent: "about"
      weight: 20

    - name: "Committees"
      url: "/about/committees/"
      parent: "about"
      weight: 30

    - name: "History"
      url: "/about/history/"
      parent: "about"
      weight: 40

    - name: "Annual Reports"
      url: "/about/reports/"
      parent: "about"
      weight: 50

  membership:
    - name: "Join IBPSA Vietnam"
      url: "/membership/join/"
      parent: "membership"
      weight: 10

    - name: "Benefits"
      url: "/membership/benefits/"
      parent: "membership"
      weight: 20

    - name: "Member Directory"
      url: "/membership/directory/"
      parent: "membership"
      weight: 30

    - name: "Fees"
      url: "/membership/fees/"
      parent: "membership"
      weight: 40

  events:
    - name: "Upcoming Events"
      url: "/events/upcoming/"
      parent: "events"
      weight: 10

    - name: "Past Events"
      url: "/events/archive/"
      parent: "events"
      weight: 20

    - name: "Webinars"
      url: "/events/webinars/"
      parent: "events"
      weight: 30

    - name: "Workshops"
      url: "/events/workshops/"
      parent: "events"
      weight: 40

  resources:
    - name: "Publications"
      url: "/resources/publications/"
      parent: "resources"
      weight: 10

    - name: "Guidelines"
      url: "/resources/guidelines/"
      parent: "resources"
      weight: 20

    - name: "Software & Tools"
      url: "/resources/tools/"
      parent: "resources"
      weight: 30

    - name: "Case Studies"
      url: "/resources/case-studies/"
      parent: "resources"
      weight: 40

    - name: "Standards"
      url: "/resources/standards/"
      parent: "resources"
      weight: 50

  news:
    - name: "Latest News"
      url: "/news/"
      parent: "news"
      weight: 10

    - name: "Newsletter Archive"
      url: "/news/newsletter/"
      parent: "news"
      weight: 20

    - name: "Announcements"
      url: "/news/announcements/"
      parent: "news"
      weight: 30

  collaboration:
    - name: "Academic Partners"
      url: "/collaboration/academic/"
      parent: "collaboration"
      weight: 10

    - name: "Industry Partners"
      url: "/collaboration/industry/"
      parent: "collaboration"
      weight: 20

    - name: "Government Relations"
      url: "/collaboration/government/"
      parent: "collaboration"
      weight: 30

    - name: "Research Projects"
      url: "/collaboration/research/"
      parent: "collaboration"
      weight: 40

  career:
    - name: "Job Board"
      url: "/career/jobs/"
      parent: "career"
      weight: 10

    - name: "Education"
      url: "/career/education/"
      parent: "career"
      weight: 20

    - name: "Certification"
      url: "/career/certification/"
      parent: "career"
      weight: 30

    - name: "Professional Development"
      url: "/career/development/"
      parent: "career"
      weight: 40

  footer:
    - name: "Privacy Policy"
      url: "/privacy/"
      weight: 10

    - name: "Terms of Service"
      url: "/terms/"
      weight: 20

    - name: "Sitemap"
      url: "/sitemap/"
      weight: 30

# Permalinks
permalinks:
  posts: "/news/:year/:month/:title/"
  events: "/events/:year/:month/:title/"

# Taxonomy
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"

# Related content
related:
  includeNewer: true
  indices:
    - name: "keywords"
      weight: 100
    - name: "tags"
      weight: 80
    - name: "categories"
      weight: 60
    - name: "date"
      weight: 10

# Image processing
imaging:
  resampleFilter: "CatmullRom"
  quality: 85
  anchor: "smart"

# Build settings
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true

# Pagination
pagination:
  pagerSize: 10
  path: "page"

# Minification
minify:
  minifyOutput: true

# Security
security:
  exec:
    allow:
      [
        "^dart-sass-embedded$",
        "^go$",
        "^npx$",
        "^postcss$",
        "^tailwindcss$",
        "^git$",
      ]
  funcs:
    getenv: ["^HUGO_", "^CI$"]
  http:
    methods: ["(?i)GET|POST"]
    urls: [".*"]
